#!/bin/bash
# CLI Resume Script — Qwen 27B Training + Learning Apparatus
# Generated: May 6, 2026 19:30 UTC
# For: New Hermes Agent CLI session

echo "======================================================================"
echo "HERMES AGENT — NEW CLI RESUME"
echo "======================================================================"
echo ""
echo "[REPO]"
echo "  cd /Users/dannygomez/hermes-agent"
echo "  git status"
echo "  git log --oneline -1"
echo ""
echo "[TRAINING STATUS]"
echo "  Step: 890/4000 (22.3%)"
echo "  Loss: 2.5775 (CE:2.217 D:1.873 SAE:0.582)"
echo "  GPU: 85.3GB / 130GB"
echo "  PID: 590094 (DGX 10.0.0.171)"
echo "  Next checkpoint: step 1000 (~30 min)"
echo "  Watcher: PID 778063 on DGX"
echo ""
echo "[QUICK STATUS]"
echo "  python3 hermes_cli/instant_context.py"
echo ""
echo "[TIERED MEMORY]"
echo "  python3 hermes_cli/subconscious/memory_daemon.py --stats"
echo ""
echo "[CHECKPOINT RECOVERY (if training crashes)]"
echo "  ssh djg6228@10.0.0.171 'bash /tmp/recovery_plan.sh'"
echo ""
echo "[DGX SSH (use sparingly during training)]"
echo "  sshpass -p '6228' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null djg6228@10.0.0.171 'tail -5 /mnt/bigssd/train_lora_sae_teacher_v1_restart.log'"
echo ""
echo "[BRANCH]"
echo "  qwen27b-training-artifacts-may3-2026"
echo "  Commit: 2928e6a13"
echo ""
echo "======================================================================"
