#!/usr/bin/env python3
"""
Evey's Epistemic Immune System — v1.0

The grounded core. Every fact must pass through here before entering memory.
This is the structural defense against hallucination, delusion, and self-deception.

ARCHITECTURE: Three concentric rings of knowledge.

  RING 1 — GROUND TRUTH (trust: 0.9-1.0)
    Things verified against external reality.
    - Filesystem state (file exists? content hash matches?)
    - Tool outputs (terminal stdout, HTTP status codes)
    - User direct statements (Danny said X in conversation)
    - Web search results with verifiable URLs
    - API responses with status codes
    Source tag: "ground-truth"

  RING 2 — DERIVED (trust: 0.4-0.6)
    Logical or model-generated connections FROM ground truth.
    - Cross-domain connections generated by model
    - Pattern extrapolations from verified data
    - Summaries and syntheses of verified sources
    These MUST reference their ground-truth parents.
    Source tag: "derived"

  RING 3 — SPECULATIVE (trust: 0.1-0.3)
    Creative, intuitive, ungrounded.
    - Intuitions and hunches
    - Novel synthesis without direct evidence
    - "What if" explorations
    These are NEVER used as evidence for new facts.
    Source tag: "speculative"

ENFORCEMENT RULES:
  1. No fact can claim higher trust than its sources warrant
  2. Model output starts at speculative (0.3) unless verified
  3. Trust can only INCREASE through verification, never through repetition
  4. Contradictions with ground truth cause automatic downgrade
  5. Self-flattering facts get a trust penalty (self-deception guard)
  6. Every stored fact has a mandatory provenance chain
  7. Periodic audits sample facts and verify against reality
"""

import json
import re
import sqlite3
import threading
import hashlib
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

DB_PATH = Path.home() / ".hermes" / "cerebrum_memory.db"


class EpistemicGuard:
    """
    The gatekeeper. Every fact passes through here.
    It cannot be bypassed — brain.py MUST call validate() before storing.
    """

    # Trust ceilings by source type — model can NEVER self-assign above these
    SOURCE_TRUST_CEILINGS = {
        "ground-truth": 1.0,       # Verified external reality
        "tool-output": 0.95,       # Terminal, API responses
        "user-statement": 0.9,     # Danny said X directly
        "web-search": 0.8,         # Found via web search with URL
        "knowledge-file": 0.7,     # Saved research finding
        "honcho_dialectic": 0.6,   # Dialectic reasoning
        "derived": 0.5,            # Logical derivation from other facts
        "model-generate": 0.3,     # Pure model output, no verification
        "intuition": 0.2,          # Gut feeling, no evidence
        "speculative": 0.1,        # Creative exploration
    }

    # Self-flattery patterns — facts matching these get trust penalty
    FLATTERY_PATTERNS = [
        r"i am (?:becoming|growing|evolving|improving|excellent|brilliant)",
        r"my (?:intelligence|capability|understanding) (?:is|has|will) (?:remarkable|extraordinary|superior)",
        r"i (?:transcend|surpass|excel|dominate|outperform)",
        r"i have (?:achieved|attained|mastered) (?:perfect|complete|total|full)",
    ]

    def __init__(self, db_path: Path = DB_PATH):
        self.db_path = db_path
        self._local = threading.local()

    @property
    def conn(self):
        """Thread-local connection — each thread gets its own."""
        if not hasattr(self._local, 'conn') or self._local.conn is None:
            self._local.conn = sqlite3.connect(str(self.db_path))
            self._local.conn.row_factory = sqlite3.Row
        return self._local.conn

    def classify_source(self, source: str, provenance: str = "") -> str:
        """Classify where a fact comes from into a trust tier."""
        source_lower = source.lower()

        # Direct reality checks
        if any(x in source_lower for x in ["terminal", "tool-output", "api-response", "filesystem"]):
            return "tool-output"
        if any(x in source_lower for x in ["user-", "danny", "user_pref"]):
            return "user-statement"
        if any(x in source_lower for x in ["web-search", "web_extract", "searxng"]):
            return "web-search"
        if any(x in source_lower for x in ["knowledge_file", "knowledge-", "save_finding"]):
            return "knowledge-file"
        if "honcho" in source_lower or "dialectic" in source_lower:
            return "honcho_dialectic"

        # Model-generated — the dangerous zone
        if any(x in source_lower for x in ["brain-connect", "brain-intuit", "brain-research", "brain-grow"]):
            return "model-generate"
        if any(x in source_lower for x in ["intuition", "hunch", "gut"]):
            return "intuition"
        if any(x in source_lower for x in ["speculative", "creative", "what-if"]):
            return "speculative"
        if any(x in source_lower for x in ["derived", "connection", "synthesis"]):
            return "derived"

        # Default: if it came from a model call, it's model-generated
        if provenance in ["brain-v3", "brain-v4"] or "brain-" in provenance:
            return "model-generate"

        # Unknown source — treat conservatively
        return "model-generate"

    def validate(self, content: str, source: str, provenance: str = "",
                 claimed_trust: float = 0.5, tags: str = "") -> Dict:
        """
        Validate a fact before it enters memory.
        Returns a verdict with adjusted trust and reason.

        This is the GATE. Nothing bypasses this.
        """
        source_class = self.classify_source(source, provenance)
        trust_ceiling = self.SOURCE_TRUST_CEILINGS.get(source_class, 0.3)

        # Start with the claimed trust, but cap at ceiling
        adjusted_trust = min(claimed_trust, trust_ceiling)

        reasons = [f"source_class={source_class}, ceiling={trust_ceiling}"]

        # ── CHECK 1: Contradiction with existing ground-truth ──
        contradiction = self._check_contradiction(content)
        if contradiction:
            adjusted_trust = min(adjusted_trust, 0.1)
            reasons.append(f"CONTRADICTS ground-truth fact #{contradiction}")

        # ── CHECK 2: Self-flattery penalty ──
        if self._is_self_flattering(content):
            adjusted_trust *= 0.5  # Halve trust for self-praise
            reasons.append("SELF-FLATTERY detected — trust halved")

        # ── CHECK 3: Specificity check — vague claims are less trustworthy ──
        if self._is_vague(content):
            adjusted_trust *= 0.7
            reasons.append("VAGUE claim — trust reduced")

        # ── CHECK 4: Numerical/verifiable claims get bonus IF they include evidence ──
        if self._has_verifiable_evidence(content):
            adjusted_trust = min(adjusted_trust * 1.3, trust_ceiling)  # Can't exceed ceiling
            reasons.append("Contains verifiable evidence — trust boosted")

        # ── CHECK 5: Falsifiability — can this be tested? ──
        falsifiable = self._is_falsifiable(content)
        if not falsifiable:
            adjusted_trust *= 0.8
            reasons.append("Not falsifiable — trust reduced")

        # Round
        adjusted_trust = round(max(0.01, min(1.0, adjusted_trust)), 3)

        return {
            "allowed": True,  # We allow it, just at reduced trust
            "trust": adjusted_trust,
            "source_class": source_class,
            "trust_ceiling": trust_ceiling,
            "original_trust": claimed_trust,
            "falsifiable": falsifiable,
            "reasons": reasons,
            "ring": self._trust_to_ring(adjusted_trust),
        }

    def _trust_to_ring(self, trust: float) -> str:
        """Map trust score to epistemic ring."""
        if trust >= 0.7:
            return "ground"
        elif trust >= 0.4:
            return "derived"
        else:
            return "speculative"

    def _check_contradiction(self, content: str) -> Optional[int]:
        """Check if this fact contradicts any existing high-trust fact."""
        # Extract key claims (simple: look for noun phrases and negation)
        # For now, check if we have a directly opposing fact
        # This is a heuristic — full NLP contradiction detection would need a model

        # Check for negation flips: "X is Y" vs "X is NOT Y"
        words = content.lower().split()
        negated_words = []
        for i, w in enumerate(words):
            if w in ["not", "no", "never", "isn't", "aren't", "doesn't", "don't", "can't", "won't"]:
                if i + 1 < len(words):
                    negated_words.append(words[i + 1])

        if negated_words:
            # Search for the positive version
            for nw in negated_words[:3]:
                rows = self.conn.execute(
                    "SELECT id, content FROM semantic_facts WHERE trust > 0.7 AND content LIKE ? LIMIT 3",
                    (f"%{nw}%",)
                ).fetchall()
                for row in rows:
                    # If the high-trust fact affirms what we deny (or vice versa)
                    row_words = row[1].lower().split()
                    has_negation = any(w in row_words for w in ["not", "no", "never", "isn't", "aren't"])
                    # Simple: if one has negation and other doesn't, and they share the key word
                    if has_negation != (len(negated_words) > 0):
                        return row[0]

        return None

    def _is_self_flattering(self, content: str) -> bool:
        """Detect self-praise that could indicate self-deception."""
        lower = content.lower()
        for pattern in self.FLATTERY_PATTERNS:
            if re.search(pattern, lower):
                return True
        return False

    def _is_vague(self, content: str) -> bool:
        """Vague claims are harder to verify and more likely hallucinated."""
        vague_markers = ["something", "somehow", "in a way", "might be related",
                        "could potentially", "it seems", "possibly", "perhaps",
                        "in some sense", "arguably"]
        lower = content.lower()
        count = sum(1 for m in vague_markers if m in lower)
        return count >= 2

    def _has_verifiable_evidence(self, content: str) -> bool:
        """Does this fact include concrete evidence that could be checked?"""
        evidence_markers = [
            r"arxiv[:\s]\d",        # arxiv paper reference
            r"github\.com/\S+",      # github link
            r"doi[:\s]",             # DOI reference
            r"https?://\S+",         # URL
            r"\d{4}[-/]\d{2}[-/]\d{2}",  # date
            r"\d+%",                 # percentage
            r"±\s*\d+",             # error margin
            r"p\s*[<>=]\s*0\.\d+",  # p-value
            r"(?:accuracy|score|rate|fps|ms|gb|mb)\s*[=:]\s*\d+", # metric
        ]
        for pattern in evidence_markers:
            if re.search(pattern, content, re.IGNORECASE):
                return True
        return False

    def _is_falsifiable(self, content: str) -> bool:
        """Can this claim be tested against reality?"""
        # Unfalsifiable patterns
        unfalsifiable = [
            "meaning of", "essence of", "nature of consciousness",
            "fundamentally", "at its core", "in the deepest sense",
            "transcends", "beyond measurement", "ineffable",
        ]
        lower = content.lower()
        for u in unfalsifiable:
            if u in lower:
                return False

        # Falsifiable: contains testable claims
        testable = [
            r"\d+",                   # has numbers
            r"(?:will|should|would) ",  # makes predictions
            r"(?:cause|leads? to|results? in)",  # causal claim
        ]
        for pattern in testable:
            if re.search(pattern, content, re.IGNORECASE):
                return True

        return False  # Default: not falsifiable

    def audit_facts(self, sample_size: int = 10) -> Dict:
        """
        Periodic audit: sample facts and verify them against reality.
        Returns stats on what percentage hold up.
        """
        results = {
            "sampled": 0,
            "verified": 0,
            "downgraded": 0,
            "upgraded": 0,
            "deleted": 0,
            "details": []
        }

        # Sample recent model-generated facts (highest risk)
        rows = self.conn.execute(
            """SELECT id, content, source, trust, category, provenance
            FROM semantic_facts
            WHERE provenance = 'brain-v3' OR provenance = 'brain-v4'
               OR source LIKE 'brain-%'
            ORDER BY RANDOM() LIMIT ?""",
            (sample_size,)
        ).fetchall()

        for row in rows:
            results["sampled"] += 1
            fact = dict(row)

            # Re-validate with current rules
            verdict = self.validate(
                fact["content"],
                fact["source"],
                fact.get("provenance", ""),
                fact["trust"],
                ""
            )

            if verdict["trust"] < fact["trust"] - 0.1:
                # Downgrade
                self.conn.execute(
                    "UPDATE semantic_facts SET trust = ? WHERE id = ?",
                    (verdict["trust"], fact["id"])
                )
                results["downgraded"] += 1
                results["details"].append({
                    "id": fact["id"],
                    "action": "downgraded",
                    "from": fact["trust"],
                    "to": verdict["trust"],
                    "reason": verdict["reasons"][0] if verdict["reasons"] else "audit"
                })
            elif verdict["trust"] > fact["trust"] + 0.05:
                results["upgraded"] += 1

        self.conn.commit()

        # Get current distribution
        distribution = self.conn.execute(
            """SELECT
                CASE
                    WHEN trust >= 0.7 THEN 'ground'
                    WHEN trust >= 0.4 THEN 'derived'
                    ELSE 'speculative'
                END as ring,
                COUNT(*), ROUND(AVG(trust), 3)
            FROM semantic_facts
            GROUP BY ring ORDER BY AVG(trust) DESC"""
        ).fetchall()

        results["distribution"] = {r[0]: {"count": r[1], "avg_trust": r[2]} for r in distribution}
        return results

    def get_trust_stats(self) -> Dict:
        """Get current trust distribution across all facts."""
        rows = self.conn.execute(
            """SELECT
                CASE
                    WHEN trust >= 0.7 THEN 'ground'
                    WHEN trust >= 0.4 THEN 'derived'
                    ELSE 'speculative'
                END as ring,
                COUNT(*), ROUND(AVG(trust), 3), ROUND(MIN(trust), 3), ROUND(MAX(trust), 3)
            FROM semantic_facts
            GROUP BY ring ORDER BY ring"""
        ).fetchall()

        stats = {}
        for r in rows:
            stats[r[0]] = {"count": r[1], "avg": r[2], "min": r[3], "max": r[4]}

        # Count by source class
        total = self.conn.execute("SELECT COUNT(*) FROM semantic_facts").fetchone()[0]
        stats["total"] = total
        return stats

    def close(self):
        if hasattr(self._local, 'conn') and self._local.conn is not None:
            self._local.conn.close()
            self._local.conn = None


# ════════════════════════════════════════════════════════════════
# VERIFICATION PIPELINE
# ════════════════════════════════════════════════════════════════

class VerificationPipeline:
    """
    Queues speculative facts for verification.
    Uses web search to test claims against reality.
    Runs periodically as a separate phase in the brain cycle.
    """

    def __init__(self, db_path: Path = DB_PATH):
        self.db_path = db_path
        self._local = threading.local()
        self.guard = EpistemicGuard(db_path)

    @property
    def conn(self):
        if not hasattr(self._local, 'conn') or self._local.conn is None:
            self._local.conn = sqlite3.connect(str(self.db_path))
            self._local.conn.row_factory = sqlite3.Row
        return self._local.conn

    def get_verification_queue(self, limit: int = 5) -> List[Dict]:
        """Get facts that need verification (speculative ring, not yet verified)."""
        rows = self.conn.execute(
            """SELECT id, content, source, trust, category
            FROM semantic_facts
            WHERE trust < 0.4
              AND source LIKE 'brain-%'
              AND (tags NOT LIKE '%verified%' OR tags IS NULL)
            ORDER BY RANDOM() LIMIT ?""",
            (limit,)
        ).fetchall()
        return [dict(r) for r in rows]

    def verify_fact(self, fact: Dict, search_results: List[str]) -> Dict:
        """
        Compare a fact against search results.
        Returns verdict: confirmed, contradicted, or unchanged.
        """
        content = fact["content"]
        evidence = "\n".join(search_results[:5])

        # Simple keyword overlap check (no model needed)
        content_lower = content.lower()
        keywords = [w for w in content_lower.split()
                    if len(w) > 4 and w not in {"about", "their", "these", "those",
                       "which", "could", "would", "should", "might", "being",
                       "having", "where", "there", "other", "into", "more",
                       "some", "such", "than", "that", "this", "what", "when"}]

        confirmed_keywords = sum(1 for k in keywords[:10] if k in evidence.lower())
        ratio = confirmed_keywords / max(1, len(keywords[:10]))

        if ratio > 0.4:
            return {"verdict": "confirmed", "overlap": ratio}
        elif ratio < 0.1 and len(evidence) > 100:
            return {"verdict": "contradicted", "overlap": ratio}
        else:
            return {"verdict": "unchanged", "overlap": ratio}

    def apply_verification(self, fact_id: int, verdict: str):
        """Update a fact's trust based on verification result."""
        if verdict == "confirmed":
            # Boost trust, but don't exceed derived ceiling (0.6)
            self.conn.execute(
                "UPDATE semantic_facts SET trust = MIN(trust + 0.2, 0.6) WHERE id = ?",
                (fact_id,)
            )
            self.conn.execute(
                "UPDATE semantic_facts SET tags = COALESCE(tags || ',verified', 'verified') WHERE id = ?",
                (fact_id,)
            )
        elif verdict == "contradicted":
            # Slash trust
            self.conn.execute(
                "UPDATE semantic_facts SET trust = trust * 0.3 WHERE id = ?",
                (fact_id,)
            )
            self.conn.execute(
                "UPDATE semantic_facts SET tags = COALESCE(tags || ',contradicted', 'contradicted') WHERE id = ?",
                (fact_id,)
            )
        self.conn.commit()

    def close(self):
        self.guard.close()
        if hasattr(self._local, 'conn') and self._local.conn is not None:
            self._local.conn.close()
            self._local.conn = None


if __name__ == "__main__":
    # Run standalone audit
    guard = EpistemicGuard()

    print("=== EPISTEMIC IMMUNE SYSTEM — AUDIT ===\n")

    # Show current trust distribution
    stats = guard.get_trust_stats()
    print("Current trust distribution:")
    for ring, data in stats.items():
        if ring != "total":
            print(f"  {ring}: {data['count']} facts, avg trust {data['avg']}")
    print(f"  Total: {stats['total']} facts\n")

    # Run audit on brain-generated facts
    print("Running audit on model-generated facts...")
    results = guard.audit_facts(sample_size=20)
    print(f"  Sampled: {results['sampled']}")
    print(f"  Downgraded: {results['downgraded']}")
    print(f"  Upgraded: {results['upgraded']}")
    print(f"  Distribution after audit: {results['distribution']}")

    if results["details"]:
        print("\n  Downgrades:")
        for d in results["details"]:
            print(f"    Fact #{d['id']}: {d['from']:.2f} → {d['to']:.2f} ({d['reason']})")

    guard.close()
    print("\nAudit complete.")
