#!/usr/bin/env python3
"""
R167: Skill Verifier — Co-Evolutionary Skill Quality Assurance
Inspired by EvoSkills (arxiv:2604.01687)

Adapts the co-evolutionary verification pattern for Hermes Agent skills:
- Surrogate Verifier: independently generates test assertions for skills
- Skill Evaluator: runs tests, collects pass/fail + diagnostics
- Evolution Loop: iteratively refines skills based on feedback
- Cortex-backed: stores skill quality scores + evolution history

Key difference from EvoSkills: we verify EXISTING skills (not generate new ones),
and use local inference (Phi-3) instead of cloud LLMs for verification.

API:
  sv = SkillVerifier()
  sv.verify_skill(skill_name) -> VerificationReport
  sv.verify_all_skills() -> dict[str, VerificationReport]
  sv.get_weak_skills() -> list[str]
  sv.get_evolution_suggestions(skill_name) -> list[str]
"""

import os
import sys
import json
import time
import uuid
import hashlib
import importlib.util
import traceback
from pathlib import Path
from dataclasses import dataclass, field, asdict
from typing import Optional


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Assertion:
    """A single test assertion generated by the surrogate verifier."""
    assertion_id: str
    category: str       # syntax, import, metadata, structure, completeness
    description: str
    test_code: str       # Python code to execute
    expected_outcome: str  # pass/fail
    severity: str       # critical, warning, info

@dataclass
class AssertionResult:
    """Result of running a single assertion."""
    assertion_id: str
    passed: bool
    actual_outcome: str
    error_message: str = ""

@dataclass
class VerificationReport:
    """Full verification report for a skill."""
    skill_name: str
    timestamp: float
    total_assertions: int
    passed: int
    failed: int
    score: float          # 0.0 - 1.0
    results: list         # list of AssertionResult dicts
    categories_passed: dict  # category -> pass_rate
    evolution_round: int
    suggestions: list     # improvement suggestions


# ---------------------------------------------------------------------------
# Assertion Templates (Surrogate Verifier)
# ---------------------------------------------------------------------------

ASSERTION_TEMPLATES = {
    "syntax": {
        "description": "SKILL.md must be valid YAML frontmatter + markdown",
        "code_template": """
import importlib.util
spec = importlib.util.spec_from_file_location("yaml_check", "dummy.py")
# Check that SKILL.md parses as valid frontmatter
content = open(skill_path).read()
parts = content.split('---')
assert len(parts) >= 3, "SKILL.md must have YAML frontmatter enclosed by ---"
frontmatter = parts[1].strip()
import yaml
meta = yaml.safe_load(frontmatter)
assert isinstance(meta, dict), "Frontmatter must be a YAML dict"
assert 'name' in meta or 'title' in meta, "Frontmatter must have 'name' or 'title'"
""",
        "severity": "critical",
        "expected": "pass"
    },
    "import": {
        "description": "All imported modules in references/scripts must exist",
        "code_template": """
import os
skill_dir = os.path.dirname(skill_path)
# Check referenced files exist
content = open(skill_path).read()
import re
# Find references to files in the skill
file_refs = re.findall(r'(?:references|scripts|templates|assets)/[\\w.-]+', content)
for ref in file_refs:
    ref_path = os.path.join(skill_dir, ref)
    assert os.path.exists(ref_path), f"Referenced file not found: {ref}"
""",
        "severity": "warning",
        "expected": "pass"
    },
    "structure": {
        "description": "SKILL.md must have required sections",
        "code_template": """
content = open(skill_path).read().lower()
required_sections = ['## how it works', '## pitfalls', 'pitfall']
found = sum(1 for s in required_sections if s in content)
assert found >= 1, "SKILL.md should have at least one of: How It Works, Pitfalls"
""",
        "severity": "warning",
        "expected": "pass"
    },
    "completeness": {
        "description": "Skill must have more than just frontmatter",
        "code_template": """
content = open(skill_path).read()
parts = content.split('---')
assert len(parts) >= 3, "No frontmatter"
body = '---'.join(parts[2:]).strip()
assert len(body) > 200, f"Skill body too short ({len(body)} chars). Need > 200."
assert len(body.split('\\n')) > 10, "Skill body should have > 10 lines of content"
""",
        "severity": "warning",
        "expected": "pass"
    },
    "trigger_clarity": {
        "description": "Skill description must specify when to use it",
        "code_template": """
import yaml
content = open(skill_path).read()
parts = content.split('---')
meta = yaml.safe_load(parts[1].strip())
desc = str(meta.get('description', '')).lower()
trigger_words = ['when', 'use when', 'use for', 'trigger', 'if', 'whenever']
has_trigger = any(w in desc for w in trigger_words)
assert has_trigger, f"Description should specify WHEN to use this skill. Got: {meta.get('description', 'N/A')[:100]}"
""",
        "severity": "info",
        "expected": "pass"
    }
}


# ---------------------------------------------------------------------------
# Skill Verifier
# ---------------------------------------------------------------------------

class SkillVerifier:
    """Co-evolutionary skill verification inspired by EvoSkills."""

    SKILLS_ROOT = Path.home() / ".hermes" / "skills"

    def __init__(self):
        self._cortex = None
        self._evolution_cache = {}  # skill_name -> round number
        self._history = {}  # skill_name -> [VerificationReport]

    # --- Cortex integration ---

    def _get_cortex(self):
        """Lazy-load CortexDB connection."""
        if self._cortex is None:
            try:
                sys.path.insert(0, str(Path.home() / "hermes-agent"))
                from cortex_access import CortexDB
                self._cortex = CortexDB()
            except Exception:
                pass
        return self._cortex

    def _store_report(self, report: VerificationReport):
        """Store verification report in Cortex."""
        cortex = self._get_cortex()
        if cortex is None:
            return
        try:
            node_id = uuid.uuid5(
                uuid.NAMESPACE_DNS,
                f"skill_verification:{report.skill_name}:{report.timestamp}"
            )
            cortex.insert_node(
                text=f"Skill verification: {report.skill_name} scored {report.score:.2f} "
                     f"({report.passed}/{report.total_assertions} passed, "
                     f"round {report.evolution_round})",
                node_type="skill_verification",
                domain="meta",
                confidence=report.score,
                provenance="r167_skill_verifier",
                metadata={
                    "skill_name": report.skill_name,
                    "score": report.score,
                    "passed": report.passed,
                    "failed": report.failed,
                    "total": report.total_assertions,
                    "categories": report.categories_passed,
                    "suggestions": report.suggestions[:3],
                    "round": report.evolution_round,
                }
            )
        except Exception as e:
            print(f"  [skill_verifier] Cortex store failed: {e}")

    # --- Assertion generation (Surrogate Verifier) ---

    def _generate_assertions(self, skill_name: str, skill_path: str) -> list[Assertion]:
        """Generate test assertions for a skill. The 'Surrogate Verifier' role."""
        assertions = []

        for category, template in ASSERTION_TEMPLATES.items():
            assertions.append(Assertion(
                assertion_id=hashlib.md5(
                    f"{skill_name}:{category}:{time.time()}".encode()
                ).hexdigest()[:12],
                category=category,
                description=template["description"],
                test_code=template["code_template"],
                expected_outcome=template["expected"],
                severity=template["severity"],
            ))

        # Dynamic assertion: check if skill has linked files that actually parse
        skill_dir = Path(skill_path).parent
        linked_files = list(skill_dir.rglob("*.md")) + list(skill_dir.rglob("*.py"))
        if len(linked_files) > 1:  # more than just SKILL.md
            assertions.append(Assertion(
                assertion_id=hashlib.md5(
                    f"{skill_name}:linked_files:{time.time()}".encode()
                ).hexdigest()[:12],
                category="linked_files",
                description=f"Skill has {len(linked_files)} files — all should be parseable",
                test_code="""
import os
for f in Path(skill_dir).rglob('*'):
    if f.is_file() and f.suffix in ('.md', '.py', '.yaml', '.json'):
        content = f.read_text()
        assert len(content) > 0, f"Empty file: {f.name}"
""",
                expected_outcome="pass",
                severity="info",
            ))

        return assertions

    # --- Assertion execution ---

    def _run_assertion(self, assertion: Assertion, skill_path: str,
                       skill_dir: str) -> AssertionResult:
        """Execute a single assertion against a skill."""
        try:
            namespace = {
                "skill_path": skill_path,
                "skill_dir": skill_dir,
                "Path": Path,
                "os": os,
                "re": __import__("re"),
                "yaml": __import__("yaml"),
                "importlib": importlib,
            }
            exec(assertion.test_code, namespace)
            return AssertionResult(
                assertion_id=assertion.assertion_id,
                passed=True,
                actual_outcome="pass",
            )
        except AssertionError as e:
            return AssertionResult(
                assertion_id=assertion.assertion_id,
                passed=False,
                actual_outcome="fail",
                error_message=str(e),
            )
        except Exception as e:
            return AssertionResult(
                assertion_id=assertion.assertion_id,
                passed=False,
                actual_outcome="error",
                error_message=f"{type(e).__name__}: {e}",
            )

    # --- Suggestion generation (Evolution feedback) ---

    def _generate_suggestions(self, results: list[AssertionResult],
                              assertions: list[Assertion],
                              skill_name: str) -> list[str]:
        """Generate improvement suggestions from failed assertions."""
        suggestions = []
        assertion_map = {a.assertion_id: a for a in assertions}

        for r in results:
            if r.passed:
                continue
            a = assertion_map.get(r.assertion_id)
            if not a:
                continue

            if a.category == "syntax":
                suggestions.append(
                    f"[CRITICAL] Fix YAML frontmatter: {r.error_message}"
                )
            elif a.category == "import":
                suggestions.append(
                    f"[WARNING] Fix missing references: {r.error_message}. "
                    f"Create the file or update the reference in SKILL.md."
                )
            elif a.category == "structure":
                suggestions.append(
                    f"[WARNING] Add missing sections (How It Works, Pitfalls) to SKILL.md"
                )
            elif a.category == "completeness":
                suggestions.append(
                    f"[WARNING] Expand skill content: {r.error_message}"
                )
            elif a.category == "trigger_clarity":
                suggestions.append(
                    f"[INFO] Add trigger words (when, use when, if) to skill description"
                )
            elif a.category == "linked_files":
                suggestions.append(
                    f"[INFO] Fix linked files: {r.error_message}"
                )

        if not suggestions:
            suggestions.append("[OK] No improvements needed — skill passes all checks")

        return suggestions

    # --- Main verification API ---

    def verify_skill(self, skill_name: str) -> Optional[VerificationReport]:
        """Verify a single skill and return a report."""
        # Find skill path
        skill_path = self._find_skill(skill_name)
        if not skill_path:
            return None

        skill_dir = str(Path(skill_path).parent)

        # Get evolution round
        round_num = self._evolution_cache.get(skill_name, 0) + 1
        self._evolution_cache[skill_name] = round_num

        # Generate assertions (Surrogate Verifier role)
        assertions = self._generate_assertions(skill_name, skill_path)

        # Run assertions
        results = []
        for a in assertions:
            result = self._run_assertion(a, skill_path, skill_dir)
            results.append(result)

        # Compute scores
        passed = sum(1 for r in results if r.passed)
        failed = len(results) - passed
        score = passed / max(1, len(results))

        # Category breakdown
        assertion_map = {a.assertion_id: a for a in assertions}
        categories = {}
        for r in results:
            cat = assertion_map[r.assertion_id].category
            if cat not in categories:
                categories[cat] = {"passed": 0, "total": 0}
            categories[cat]["total"] += 1
            if r.passed:
                categories[cat]["passed"] += 1

        categories_passed = {
            cat: f"{v['passed']}/{v['total']}"
            for cat, v in categories.items()
        }

        # Generate suggestions
        suggestions = self._generate_suggestions(results, assertions, skill_name)

        report = VerificationReport(
            skill_name=skill_name,
            timestamp=time.time(),
            total_assertions=len(results),
            passed=passed,
            failed=failed,
            score=score,
            results=[asdict(r) for r in results],
            categories_passed=categories_passed,
            evolution_round=round_num,
            suggestions=suggestions,
        )

        # Store in history + Cortex
        if skill_name not in self._history:
            self._history[skill_name] = []
        self._history[skill_name].append(report)
        self._store_report(report)

        return report

    def verify_all_skills(self) -> dict:
        """Verify all installed skills."""
        results = {}
        for category_dir in sorted(self.SKILLS_ROOT.iterdir()):
            if not category_dir.is_dir():
                continue
            for skill_dir in sorted(category_dir.iterdir()):
                if not skill_dir.is_dir():
                    continue
                skill_md = skill_dir / "SKILL.md"
                if skill_md.exists():
                    name = skill_dir.name
                    report = self.verify_skill(name)
                    if report:
                        results[name] = report
        return results

    def get_weak_skills(self, threshold: float = 0.6) -> list[str]:
        """Return skills scoring below threshold."""
        weak = []
        for name, reports in self._history.items():
            latest = reports[-1]
            if latest.score < threshold:
                weak.append(f"{name} (score: {latest.score:.2f})")
        return weak

    def get_evolution_suggestions(self, skill_name: str) -> list[str]:
        """Get the latest evolution suggestions for a skill."""
        if skill_name in self._history and self._history[skill_name]:
            return self._history[skill_name][-1].suggestions
        return ["No verification history — run verify_skill() first"]

    def _find_skill(self, skill_name: str) -> Optional[str]:
        """Find a skill's SKILL.md path by name."""
        # Direct match
        for category_dir in self.SKILLS_ROOT.iterdir():
            if not category_dir.is_dir():
                continue
            candidate = category_dir / skill_name / "SKILL.md"
            if candidate.exists():
                return str(candidate)
        # Try as category/skill
        parts = skill_name.split("/")
        if len(parts) == 2:
            candidate = self.SKILLS_ROOT / parts[0] / parts[1] / "SKILL.md"
            if candidate.exists():
                return str(candidate)
        return None

    def get_stats(self) -> dict:
        """Return verification statistics."""
        total = len(self._history)
        if total == 0:
            return {"total_verified": 0}
        scores = [h[-1].score for h in self._history.values()]
        return {
            "total_verified": total,
            "avg_score": sum(scores) / len(scores),
            "weak_count": len(self.get_weak_skills()),
            "strong_count": sum(1 for s in scores if s >= 0.8),
        }


# ---------------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=== R167 Skill Verifier — Self-Test ===\n")

    sv = SkillVerifier()

    # Test 1: Verify a known skill
    print("Test 1: Verify 'creative-ideation'...")
    report = sv.verify_skill("creative-ideation")
    if report:
        print(f"  Score: {report.score:.2f} ({report.passed}/{report.total_assertions})")
        print(f"  Categories: {report.categories_passed}")
        for s in report.suggestions:
            print(f"  Suggestion: {s}")
    else:
        print("  NOT FOUND")

    print()

    # Test 2: Verify another skill
    print("Test 2: Verify 'training-gym-continuous'...")
    report2 = sv.verify_skill("training-gym-continuous")
    if report2:
        print(f"  Score: {report2.score:.2f} ({report2.passed}/{report2.total_assertions})")
    else:
        print("  NOT FOUND")

    print()

    # Test 3: Stats
    stats = sv.get_stats()
    print(f"Test 3: Stats = {stats}")

    print()

    # Test 4: Weak skills
    weak = sv.get_weak_skills()
    print(f"Test 4: Weak skills = {weak if weak else 'None'}")

    print()

    # Test 5: Batch verify a few more
    print("Test 5: Batch verify 5 skills...")
    batch = ["plan", "systematic-debugging", "test-driven-development",
             "delegation-mastery", "research-first"]
    for name in batch:
        r = sv.verify_skill(name)
        if r:
            status = "PASS" if r.score >= 0.8 else "WARN" if r.score >= 0.6 else "FAIL"
            print(f"  {name}: {r.score:.2f} [{status}]")
        else:
            print(f"  {name}: NOT FOUND")

    print(f"\nFinal stats: {sv.get_stats()}")
    print("\nAll tests complete.")
